# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Optional open-source local-model runtime; model weights have separate licenses
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# Ollama: Open-source model runtime; no models pulled or services started
# License: MIT (open-source)
brew "ollama"
