# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Opt-in AI browser, editor and assistant
# Unpinned: installs Homebrew's available version, not a frozen 2026 release.

# Aside: AI browser for tasks across websites; review account and data-access settings
cask "aside"

# Cursor: AI-assisted code editor; alternative to VS Code
cask "cursor"

# Claude: Desktop AI assistant; account and plan terms apply
cask "claude"
