# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Open-source everyday desktop utilities and media players; choose what you need
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# VLC: General-purpose media player; alternative to IINA
# License: GPL-2.0-or-later (player) (open-source)
cask "vlc"

# IINA: Mac-native media player; alternative to VLC
# License: GPL-3.0-only (open-source)
cask "iina"

# Stats: Menu-bar system resource information
# License: MIT (open-source)
cask "stats"

# Maccy: Clipboard history; configure sensitive-data exclusions
# License: MIT (open-source)
cask "maccy"

# LocalSend: Local-network file transfers across devices
# License: Apache-2.0 (open-source)
cask "localsend"
