# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Containers, Kubernetes and infrastructure tools
# Unpinned: installs Homebrew's available version, not a frozen 2026 release.

# OrbStack: Local containers and Linux machines; check commercial licensing
cask "orbstack"

# kubectl: Operate Kubernetes clusters; credentials are not configured
brew "kubernetes-cli"

# Helm: Kubernetes package management
brew "helm"

# K9s: Terminal interface for Kubernetes
brew "k9s"

# OpenTofu: Infrastructure as code
brew "opentofu"
