# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Open-source containers, Kubernetes and infrastructure tools; no services started
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# Colima: Local container VM/runtime; not started automatically
# License: MIT (open-source)
brew "colima"

# Docker CLI: Open-source CLI only, not Docker Desktop
# License: Apache-2.0 (open-source)
brew "docker"

# Docker Compose: Compose CLI plugin; discovery may need manual configuration
# License: Apache-2.0 (open-source)
brew "docker-compose"

# kubectl: Kubernetes CLI; cluster access is not configured
# License: Apache-2.0 (open-source)
brew "kubernetes-cli"

# Helm: Kubernetes package management
# License: Apache-2.0 (open-source)
brew "helm"

# K9s: Terminal interface for Kubernetes
# License: Apache-2.0 (open-source)
brew "k9s"

# OpenTofu: Open-source infrastructure as code
# License: MPL-2.0 (open-source)
brew "opentofu"
