# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Editor, terminal and runtime tooling
# Unpinned: installs Homebrew's available version, not a frozen 2026 release.

# Ghostty: Native GPU-accelerated terminal
cask "ghostty"

# Visual Studio Code: General-purpose editor
cask "visual-studio-code"

# mise: Manage project language runtimes explicitly
brew "mise"

# uv: Python packages, projects and environments
brew "uv"
