# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Open-source editor, terminal and development workflow tools
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# VSCodium: Open-source editor distribution; check extension compatibility
# License: MIT (open-source)
cask "vscodium"

# Ghostty: Native GPU-accelerated terminal
# License: MIT (open-source)
cask "ghostty"

# mise: Project-specific language runtimes; no versions activated automatically
# License: MIT (open-source)
brew "mise"

# uv: Python packages, projects and environments
# License: Apache-2.0 OR MIT (open-source)
brew "uv"

# direnv: Per-project environment variables; only trust reviewed envrc files
# License: MIT (open-source)
brew "direnv"

# ShellCheck: Static checks for shell scripts
# License: GPL-3.0-or-later (open-source)
brew "shellcheck"

# just: Project command runner
# License: CC0-1.0 (open-source)
brew "just"

# HTTPie CLI: Readable HTTP requests in the terminal
# License: BSD-3-Clause (open-source)
brew "httpie"
