# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Small open-source foundation: browser, passwords, windows and core CLI
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# Firefox: Everyday open-source browser
# License: MPL-2.0 (primary) (open-source)
cask "firefox"

# KeePassXC: Local encrypted password database; choose your own backup and sync
# License: GPL-2.0-only OR GPL-3.0-only (core) (open-source)
cask "keepassxc"

# Rectangle: Keyboard-driven window positioning
# License: MIT (open-source)
cask "rectangle"

# Git: Version control
# License: GPL-2.0-only AND GPL-2.0-or-later AND LGPL-2.1-or-later AND BSD-3-Clause AND MIT (open-source)
brew "git"

# GitHub CLI: Repositories, pull requests and issues from your terminal
# License: MIT (open-source)
brew "gh"

# jq: Inspect and transform JSON
# License: MIT (open-source)
brew "jq"
