# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Small foundation: CLI utilities, passwords and windows
# Unpinned: installs Homebrew's available version, not a frozen 2026 release.

# Git: Version control
brew "git"

# GitHub CLI: Repositories, pull requests and issues from your terminal
brew "gh"

# jq: Inspect and transform JSON
brew "jq"

# ripgrep: Fast code search
brew "ripgrep"

# fzf: Interactive fuzzy finding
brew "fzf"

# Bitwarden: Password manager; account and setup required
cask "bitwarden"

# Rectangle: Keyboard-driven window positioning
cask "rectangle"
