# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Open-source alternatives, notes and backup tools
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# Zed: Alternative editor; hosted AI services are separate
# License: GPL-3.0-or-later; Apache-2.0 where marked (open-source)
cask "zed"

# iTerm2: Alternative terminal to Ghostty
# License: GPL-3.0-or-later (combined distribution) (open-source)
cask "iterm2"

# Neovim: Terminal-based editor
# License: Apache-2.0 (open-source)
brew "neovim"

# Joplin: Notes app with optional sync services
# License: AGPL-3.0-or-later (default) (open-source)
cask "joplin"

# restic: Encrypted backup CLI; destination and recovery setup are manual
# License: BSD-2-Clause (open-source)
brew "restic"
