# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Alternatives: review before installing overlapping tools
# Unpinned: installs Homebrew's available version, not a frozen 2026 release.

# Zed: Alternative code editor
cask "zed"

# iTerm2: Alternative terminal
cask "iterm2"

# Raycast: Launcher and productivity tools; check current architecture support
cask "raycast"

# Obsidian: Local Markdown notes; optional services have separate terms
cask "obsidian"
