# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Explicit opt-in exceptions: proprietary, mixed-license or not verified open source
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# Aside: Optional AI browser; review account, permission and processing terms
# License: Vendor terms; not verified open source (not-verified-open-source)
cask "aside"

# Cursor: Optional AI editor with vendor-controlled service terms
# License: Vendor terms; not verified open source (not-verified-open-source)
cask "cursor"

# Claude: Optional desktop AI assistant; account and plan terms apply
# License: Vendor terms; not verified open source (not-verified-open-source)
cask "claude"

# Microsoft Visual Studio Code: Microsoft binary distribution; VSCodium is the preferred open-source path
# License: Microsoft product license (not-verified-open-source)
cask "visual-studio-code"

# OrbStack: Optional container app; Colima is the open-source path
# License: Vendor terms; not verified open source (not-verified-open-source)
cask "orbstack"

# Raycast: Optional launcher; verify current ARM64 support and plan terms
# License: Vendor terms; not verified open source (not-verified-open-source)
cask "raycast"

# Obsidian: Optional notes app; Joplin is the open-source path
# License: Vendor terms; not verified open source (not-verified-open-source)
cask "obsidian"

# Bitwarden: Optional password manager with mixed-license source; existing vaults are unchanged
# License: GPL-3.0 plus Bitwarden License modules (mixed)
cask "bitwarden"
