# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.
# Optional open-source command-line productivity utilities
# Unpinned: installs Homebrew available versions, not frozen 2026 releases.

# ripgrep: Fast code and text search
# License: Unlicense (open-source)
brew "ripgrep"

# fd: Friendly file finding
# License: Apache-2.0 OR MIT (open-source)
brew "fd"

# fzf: Interactive fuzzy finding
# License: MIT (open-source)
brew "fzf"

# bat: Syntax-highlighted file previews
# License: Apache-2.0 OR MIT (open-source)
brew "bat"

# eza: Modern directory listings
# License: EUPL-1.2 (open-source)
brew "eza"

# zoxide: Jump to frequently used directories; shell activation is manual
# License: MIT (open-source)
brew "zoxide"

# Starship: Cross-shell prompt; shell activation is manual
# License: ISC (open-source)
brew "starship"

# tmux: Persistent terminal sessions and panes
# License: ISC (open-source)
brew "tmux"

# btop: Terminal system-resource monitor
# License: Apache-2.0 (open-source)
brew "btop"

# tlrc: Official Rust tldr client for concise command examples
# License: MIT (open-source)
brew "tlrc"
