#!/usr/bin/env node
// Maintainer tooling only. End users do not need Node to run setup.sh.
import { readFile, writeFile, rename, rm, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const readJSON = async file => JSON.parse(await readFile(path.join(root, file), 'utf8'));
const catalog = await readJSON('catalog/apps.json');
const verified = await readJSON('catalog/verified.json');
const command = process.argv[2] || 'check';
const allowed = ['check', 'generate', 'audit', 'refresh'];
if (!allowed.includes(command) || process.argv.length > 3) throw new Error(`Usage: node scripts/catalog.mjs ${allowed.join('|')}`);

function validate() {
  if (catalog.schemaVersion !== 1 || catalog.edition !== 2026) throw new Error('Unsupported catalog schema/edition');
  const seen = new Set();
  for (const p of catalog.packages) {
    if (!/^[a-z0-9][a-z0-9@+.-]*$/.test(p.id)) throw new Error(`Invalid package identifier: ${p.id}`);
    if (!['formula', 'cask'].includes(p.kind)) throw new Error(`Invalid package kind: ${p.kind}`);
    if (!Object.hasOwn(catalog.profiles, p.profile)) throw new Error(`Unknown profile: ${p.profile}`);
    const key = `${p.kind}/${p.id}`;
    if (seen.has(key)) throw new Error(`Duplicate: ${key}`);
    seen.add(key);
    if (p.source !== `https://formulae.brew.sh/api/${key}.json`) throw new Error(`Unexpected source: ${key}`);
    if (!p.homepage.startsWith('https://')) throw new Error(`Homepage must use HTTPS: ${key}`);
    for (const value of [p.name, p.why]) if (/[\r\n|]/.test(value)) throw new Error(`Unsafe description: ${key}`);
    const checked = verified.packages.find(v => v.kind === p.kind && v.id === p.id);
    if (!checked || checked.deprecated || checked.disabled || !checked.version) throw new Error(`No usable verified record for ${key}`);
  }
  if (verified.packages.length !== seen.size || !Number.isFinite(Date.parse(verified.checkedAt))) throw new Error('Invalid verification snapshot');
}

function generatedFiles(snapshot) {
  const files = new Map();
  for (const [profile, description] of Object.entries(catalog.profiles)) {
    const entries = catalog.packages.filter(p => p.profile === profile).map(p => `# ${p.name}: ${p.why}\n${p.kind === 'formula' ? 'brew' : 'cask'} "${p.id}"`);
    files.set(`profiles/${profile}.Brewfile`, `# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.\n# ${description}\n# Unpinned: installs Homebrew's available version, not a frozen 2026 release.\n\n${entries.join('\n\n')}\n`);
  }
  const lines = ['# App catalog', '', `Homebrew metadata snapshot: **${snapshot.checkedAt}**.`, '', 'These are curated options, not a claim that every app is best for everyone. Versions below are observations, not pins. Metadata verification is not installation testing, a security audit, or confirmation of the newest vendor release. Check vendor licensing, account requirements and supported hardware before installing.', '', 'Profiles are additive only when explicitly selected. The default is `essentials`; `extras` contains alternatives, not prerequisites.', ''];
  for (const [profile, description] of Object.entries(catalog.profiles)) {
    lines.push(`## ${profile}`, '', description, '', '| App | Why it is here | Observed Homebrew version | Source |', '| --- | --- | --- | --- |');
    for (const p of catalog.packages.filter(p => p.profile === profile)) {
      const v = snapshot.packages.find(v => v.kind === p.kind && v.id === p.id);
      lines.push(`| [${p.name}](${p.homepage}) | ${p.why} | \`${v.version}\` | [${p.kind}/${p.id}](${p.source}) |`);
    }
    lines.push('');
  }
  lines.push('## Compatibility notes', '', '- Aside: vendor help states macOS 15+, while the checked Homebrew cask declares macOS 13+. Follow the stricter vendor requirement until reconciled: [vendor help](https://docs.aside.com/help/get-started).', '- Raycast: the checked Homebrew metadata restricts the cask to ARM64. It is optional; do not assume Intel support.', '- This project targets current Apple Silicon Macs on macOS 15+; per-app requirements can be higher. Intel compatibility is not verified.', '- AI applications can transmit data to external services. Review their permissions, retention terms and workspace policies. Installation does not configure or approve data access.', '- Paid plans and commercial-use restrictions are vendor-controlled. Inclusion is not an endorsement, affiliation or free-license promise.', '');
  files.set('docs/apps.md', lines.join('\n'));
  return files;
}

async function saveGenerated(snapshot, check = false) {
  for (const [file, text] of generatedFiles(snapshot)) {
    if (check) {
      if (await readFile(path.join(root, file), 'utf8') !== text) throw new Error(`Generated file is stale: ${file}. Run npm run generate.`);
    } else await writeFile(path.join(root, file), text);
  }
}

async function inspectLive() {
  // Bound concurrency and reject partial results. Existing verification remains untouched on failure.
  const packages = [];
  for (let offset = 0; offset < catalog.packages.length; offset += 4) {
    const batch = await Promise.all(catalog.packages.slice(offset, offset + 4).map(async p => {
      const response = await fetch(p.source, { signal: AbortSignal.timeout(20000) });
      if (!response.ok) throw new Error(`${p.id}: HTTP ${response.status}`);
      const d = await response.json();
      const version = d.version ?? d.versions?.stable;
      if (!version || (d.token ?? d.name) !== p.id) throw new Error(`Unexpected metadata: ${p.id}`);
      if (d.disabled || d.deprecated) throw new Error(`${p.id}: disabled or deprecated; review or remove it`);
      return { kind: p.kind, id: p.id, version, homepage: d.homepage, desc: d.desc, deprecated: Boolean(d.deprecated), disabled: Boolean(d.disabled), ...(d.depends_on ? { depends_on: d.depends_on } : {}), token: d.token ?? d.name };
    }));
    packages.push(...batch);
  }
  return { checkedAt: new Date().toISOString(), scope: verified.scope, packages };
}

validate();
if (command === 'check') {
  await saveGenerated(verified, true);
  console.log(`Catalog and generated files valid: ${catalog.packages.length} packages, ${Object.keys(catalog.profiles).length} profiles.`);
} else if (command === 'generate') {
  await saveGenerated(verified);
  console.log('Generated Brewfiles and docs/apps.md.');
} else {
  await mkdir(path.join(root, 'reports'), { recursive: true });
  try {
    const live = await inspectLive();
    const changes = [];
    for (const p of live.packages) {
      const old = verified.packages.find(v => v.id === p.id && v.kind === p.kind);
      if (old.version !== p.version) changes.push(`${p.id}: ${old.version} -> ${p.version}`);
      for (const key of ['homepage', 'depends_on']) if (JSON.stringify(old[key]) !== JSON.stringify(p[key])) changes.push(`${p.id}: ${key} changed; review compatibility/docs`);
    }
    const lines = ['# Homebrew freshness check', '', `Checked: ${live.checkedAt}`, '', `${live.packages.length} package records are available and not deprecated/disabled.`, '', changes.length ? '## Review needed\n\n' + changes.map(c => `- ${c}`).join('\n') : 'No version or compatibility-metadata changes detected against the committed snapshot.', '', 'Scope: metadata only. This does not verify vendor-latest versions or clean-Mac installations.', ''];
    await writeFile(path.join(root, 'reports/freshness.md'), lines.join('\n'));
    await writeFile(path.join(root, 'reports/freshness.json'), JSON.stringify({ checkedAt: live.checkedAt, ok: true, changes }, null, 2) + '\n');
    if (command === 'refresh') {
      const temp = path.join(root, 'catalog/verified.json.tmp');
      await writeFile(temp, JSON.stringify(live, null, 2) + '\n');
      await rename(temp, path.join(root, 'catalog/verified.json'));
      await saveGenerated(live);
      console.log('Refreshed metadata and generated files. Review the diff before committing.');
    } else {
      console.log(lines.join('\n'));
      // Version drift needs review; scheduled workflow opens or updates one issue.
      if (changes.length) process.exitCode = 2;
    }
  } catch (error) {
    await rm(path.join(root, 'catalog/verified.json.tmp'), { force: true });
    await writeFile(path.join(root, 'reports/freshness.md'), `# Freshness check incomplete\n\n${error.message}\n\nThe last valid committed snapshot has been preserved. A failed fetch does not prove a package is unavailable.\n`);
    await writeFile(path.join(root, 'reports/freshness.json'), JSON.stringify({ checkedAt: new Date().toISOString(), ok: false, error: error.message }, null, 2) + '\n');
    console.error(error.message);
    process.exitCode = 1;
  }
}
