#!/usr/bin/env node
// Maintainer tooling only. End users do not need Node to run setup.sh.
import { readFile, writeFile, rename, rm, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const readJSON = async file => JSON.parse(await readFile(path.join(root, file), 'utf8'));
const catalog = await readJSON('catalog/apps.json');
const verified = await readJSON('catalog/verified.json');
const command = process.argv[2] || 'check';
const allowed = ['check', 'generate', 'audit', 'refresh'];
if (!allowed.includes(command) || process.argv.length > 3) throw new Error(`Usage: node scripts/catalog.mjs ${allowed.join('|')}`);

function validate() {
  if (catalog.schemaVersion !== 1 || catalog.edition !== 2026) throw new Error('Unsupported catalog schema/edition');
  const seen = new Set();
  for (const [name, description] of Object.entries(catalog.profiles)) {
    if (!/^[a-z][a-z0-9-]*$/.test(name)) throw new Error('Invalid profile name');
    if (typeof description !== 'string' || /[\r\n]/.test(description)) throw new Error('Invalid profile description');
  }
  for (const p of catalog.packages) {
    if (!/^[a-z0-9][a-z0-9@+.-]*$/.test(p.id)) throw new Error(`Invalid package identifier: ${p.id}`);
    if (!['formula', 'cask'].includes(p.kind)) throw new Error(`Invalid package kind: ${p.kind}`);
    if (!Object.hasOwn(catalog.profiles, p.profile)) throw new Error(`Unknown profile: ${p.profile}`);
    const key = `${p.kind}/${p.id}`;
    if (seen.has(key)) throw new Error(`Duplicate: ${key}`);
    seen.add(key);
    if (p.source !== `https://formulae.brew.sh/api/${key}.json`) throw new Error(`Unexpected source: ${key}`);
    if (!p.homepage.startsWith('https://')) throw new Error(`Homepage must use HTTPS: ${key}`);
    for (const value of [p.name, p.why]) if (/[\r\n|]/.test(value)) throw new Error(`Unsafe description: ${key}`);
    if (!p.license || !['open-source', 'mixed', 'not-verified-open-source'].includes(p.license.status)) throw new Error('Missing license classification: ' + key);
    if (p.profile !== 'optional' && p.license.status !== 'open-source') throw new Error('Non-open-source entry outside optional: ' + key);
    if (!p.license.label || !p.license.evidence?.startsWith('https://') || !Number.isFinite(Date.parse(p.license.checkedAt))) throw new Error('Missing license evidence: ' + key);
    if (/[\r\n|]/.test(p.license.label)) throw new Error('Unsafe license label: ' + key);
    const checked = verified.packages.find(v => v.kind === p.kind && v.id === p.id);
    if (command !== 'refresh' && (!checked || checked.deprecated || checked.disabled || !checked.version)) throw new Error(`No usable verified record for ${key}`);
    if (command !== 'refresh' && p.kind === 'formula' && checked.license !== p.license.label) throw new Error('Formula license evidence is stale: ' + key);
  }
  if ((command !== 'refresh' && verified.packages.length !== seen.size) || !Number.isFinite(Date.parse(verified.checkedAt))) throw new Error('Invalid verification snapshot');
}

function generatedFiles(snapshot) {
  const files = new Map();
  for (const [profile, description] of Object.entries(catalog.profiles)) {
    const entries = catalog.packages.filter(p => p.profile === profile).map(p => '# ' + p.name + ': ' + p.why + '\n# License: ' + p.license.label + ' (' + p.license.status + ')\n' + (p.kind === 'formula' ? 'brew' : 'cask') + ' "' + p.id + '"');
    files.set('profiles/' + profile + '.Brewfile', '# Generated by node scripts/catalog.mjs generate. Edit catalog/apps.json instead.\n# ' + description + '\n# Unpinned: installs Homebrew available versions, not frozen 2026 releases.\n\n' + entries.join('\n\n') + '\n');
  }
  const lines = ['# App catalog', '', '**Open-source first. Choose what you need, not everything on the list.**', '', 'Homebrew metadata snapshot: **' + snapshot.checkedAt + '**.', '', 'Versions are observations, not pins. Open-source classifications refer to upstream declared licenses; they are not a full bundled-dependency audit or a promise that hosted services are free. Follow the evidence links. Formula licenses come from Homebrew metadata; cask licenses are human-reviewed upstream evidence.', '', 'Metadata checks are not clean-Mac installation tests, security reviews, upstream license revalidation or proof of the newest vendor release. The optional profile is the only place for proprietary, mixed-license or unverified-open-source choices.', ''];
  for (const [profile, description] of Object.entries(catalog.profiles)) {
    lines.push('## ' + profile, '', description, '', '| App | Purpose | License / evidence | Homebrew version |', '| --- | --- | --- | --- |');
    for (const p of catalog.packages.filter(p => p.profile === profile)) {
      const v = snapshot.packages.find(v => v.kind === p.kind && v.id === p.id);
      lines.push('| [' + p.name + '](' + p.homepage + ') | ' + p.why + ' | [' + p.license.label + '](' + p.license.evidence + ') (' + p.license.status + ') | [' + v.version + '](' + p.source + ') |');
    }
    lines.push('');
  }
  lines.push('## Important distinctions', '', '- VSCodium is the preferred editor distribution. Microsoft VS Code binaries have different terms; some Microsoft extensions and services are restricted in alternative distributions.', '- Docker and Docker Compose here are CLI packages, not Docker Desktop. Colima is installed but not started; see the after-install checklist for Compose discovery.', '- Ollama is an open-source runtime, not a license for model weights. No model is downloaded and no server is started automatically.', '- Zed and Joplin have optional commercial services; their app-source licenses do not make those services free.', '- KeePassXC is the default local password-database choice. Bitwarden remains optional because its source tree has GPL and Bitwarden-specific licensed portions; existing vaults and preferences are not changed.', '- Aside: vendor help states macOS 15+, while the checked cask declares macOS 13+. Follow the stricter [vendor requirement](https://docs.aside.com/help/get-started). It is optional, not an open-source recommendation.', '- Raycast is optional; the checked metadata restricts its cask to ARM64. Do not assume Intel support.', '- Current Apple Silicon Macs on macOS 15+ are the target, subject to higher per-app requirements. Intel and clean-Mac installs are not comprehensively verified.', '- Clipboard managers can capture sensitive data. AI tools can transmit it to external services. Review permissions, retention, model licenses and workplace policy before use.', '', 'Per-entry license-review timestamps and evidence are recorded in [catalog/apps.json](../catalog/apps.json). See [after-install.md](after-install.md) for manual configuration.', '');
  files.set('docs/apps.md', lines.join('\n'));
  return files;
}

async function saveGenerated(snapshot, check = false) {
  for (const [file, text] of generatedFiles(snapshot)) {
    if (check) {
      if (await readFile(path.join(root, file), 'utf8') !== text) throw new Error(`Generated file is stale: ${file}. Run npm run generate.`);
    } else await writeFile(path.join(root, file), text);
  }
}

async function inspectLive() {
  // Bound concurrency and reject partial results. Existing verification remains untouched on failure.
  const packages = [];
  for (let offset = 0; offset < catalog.packages.length; offset += 4) {
    const batch = await Promise.all(catalog.packages.slice(offset, offset + 4).map(async p => {
      const response = await fetch(p.source, { signal: AbortSignal.timeout(20000) });
      if (!response.ok) throw new Error(`${p.id}: HTTP ${response.status}`);
      const d = await response.json();
      const version = d.version ?? d.versions?.stable;
      if (!version || (d.token ?? d.name) !== p.id) throw new Error(`Unexpected metadata: ${p.id}`);
      if (d.disabled || d.deprecated) throw new Error(`${p.id}: disabled or deprecated; review or remove it`);
      return { kind: p.kind, id: p.id, version, homepage: d.homepage, desc: d.desc, deprecated: Boolean(d.deprecated), disabled: Boolean(d.disabled), ...(d.depends_on ? { depends_on: d.depends_on } : {}), token: d.token ?? d.name, license: d.license ?? null };
    }));
    packages.push(...batch);
  }
  return { checkedAt: new Date().toISOString(), scope: verified.scope, packages };
}

validate();
if (command === 'check') {
  await saveGenerated(verified, true);
  console.log(`Catalog and generated files valid: ${catalog.packages.length} packages, ${Object.keys(catalog.profiles).length} profiles.`);
} else if (command === 'generate') {
  await saveGenerated(verified);
  console.log('Generated Brewfiles and docs/apps.md.');
} else {
  await mkdir(path.join(root, 'reports'), { recursive: true });
  try {
    const live = await inspectLive();
    const changes = [];
    for (const p of live.packages) {
      const old = verified.packages.find(v => v.id === p.id && v.kind === p.kind);
      if (!old) { changes.push(p.id + ': new package'); continue; }
      if (old.version !== p.version) changes.push(`${p.id}: ${old.version} -> ${p.version}`);
      for (const key of ['homepage', 'depends_on', 'license']) if (JSON.stringify(old[key]) !== JSON.stringify(p[key])) changes.push(`${p.id}: ${key} changed; review compatibility/docs`);
    }
    const lines = ['# Homebrew freshness check', '', `Checked: ${live.checkedAt}`, '', `${live.packages.length} package records are available and not deprecated/disabled.`, '', changes.length ? '## Review needed\n\n' + changes.map(c => `- ${c}`).join('\n') : 'No version or compatibility-metadata changes detected against the committed snapshot.', '', 'Scope: metadata only. This does not verify vendor-latest versions or clean-Mac installations.', ''];
    await writeFile(path.join(root, 'reports/freshness.md'), lines.join('\n'));
    await writeFile(path.join(root, 'reports/freshness.json'), JSON.stringify({ checkedAt: live.checkedAt, ok: true, changes }, null, 2) + '\n');
    if (command === 'refresh') {
      for (const p of catalog.packages.filter(p => p.kind === 'formula')) if (live.packages.find(v => v.id === p.id && v.kind === p.kind).license !== p.license.label) throw new Error('Formula license changed; review catalog entry first: ' + p.id);
      const temp = path.join(root, 'catalog/verified.json.tmp');
      await writeFile(temp, JSON.stringify(live, null, 2) + '\n');
      await rename(temp, path.join(root, 'catalog/verified.json'));
      await saveGenerated(live);
      console.log('Refreshed metadata and generated files. Review the diff before committing.');
    } else {
      console.log(lines.join('\n'));
      // Version drift needs review; scheduled workflow opens or updates one issue.
      if (changes.length) process.exitCode = 2;
    }
  } catch (error) {
    await rm(path.join(root, 'catalog/verified.json.tmp'), { force: true });
    await writeFile(path.join(root, 'reports/freshness.md'), `# Freshness check incomplete\n\n${error.message}\n\nThe last valid committed snapshot has been preserved. A failed fetch does not prove a package is unavailable.\n`);
    await writeFile(path.join(root, 'reports/freshness.json'), JSON.stringify({ checkedAt: new Date().toISOString(), ok: false, error: error.message }, null, 2) + '\n');
    console.error(error.message);
    process.exitCode = 1;
  }
}
